In [1]:
import numpy as np
array=np.random.random(size=(10,1))
print(array)
mean=array.mean()
print(mean)

[[0.88660522]
 [0.68164547]
 [0.64832061]
 [0.55961746]
 [0.3029799 ]
 [0.84726558]
 [0.87625734]
 [0.68325961]
 [0.85470645]
 [0.3322938 ]]
0.6672951430804734


In [2]:
array1=np.random.random(size=(20,1))
print(array1)
var=array1.var()
std=array1.std()
print(var)
print(std)

[[0.29783573]
 [0.29400427]
 [0.17735199]
 [0.34715648]
 [0.82059448]
 [0.52816832]
 [0.2331379 ]
 [0.271828  ]
 [0.65328306]
 [0.71935862]
 [0.0796532 ]
 [0.63970759]
 [0.61196097]
 [0.58203172]
 [0.66773241]
 [0.7894294 ]
 [0.94407888]
 [0.65202327]
 [0.92617959]
 [0.27620996]]
0.06377730792214259
0.2525416954131388


In [3]:
arr=np.random.random(size=(10,20))
arr1=np.random.random(size=(20,25))
arr2=np.matmul(arr,arr1)
print(arr2)
arr2.sum()

[[4.32031737 3.95552857 4.22274403 4.21529281 2.93903189 4.00432947
  3.38602142 3.20967144 3.7448726  5.46141362 5.41574673 4.26517574
  4.5182361  5.38091333 4.07401572 5.00097636 5.19916217 4.94364906
  5.09957531 5.38602766 4.86509377 3.07581156 3.32783583 5.49140077
  5.57869224]
 [4.2612563  3.84001688 4.90042258 5.75101863 3.80637118 3.38572631
  3.49949273 3.56511282 4.27180136 5.07693216 6.07708238 4.88784213
  5.13290111 5.89789903 4.23720865 4.31280733 5.16602111 4.6851341
  5.26169713 5.28227557 5.23540099 3.12483057 3.57613194 6.83233086
  6.01138078]
 [4.06233089 4.11140648 5.33178359 4.79398434 3.15530265 3.9994404
  4.70697293 3.17417131 4.1977621  6.10872385 5.23444712 4.54126555
  3.96339715 5.70316921 4.08655776 4.44562128 5.58101155 5.12416843
  5.30613447 4.64187313 5.32758132 3.3445582  3.65831508 6.04727018
  5.26992832]
 [4.38581919 5.7994541  6.25660158 6.26405993 4.72019396 4.63386081
  5.20909289 4.76555885 5.75969799 6.86206652 7.17767265 6.09669373
  5.5583

1288.7996564842692

In [4]:
array2=np.random.random(size=(10,1))
print(array2)
print("*"*80)
array3=np.ndarray((10,1))
def func(x):
    return 1/1+ np.exp(-x)
List=list()
List1=list()
for i in range(0,array2.shape[0]):
    List.clear()
    for j in array2[i]:
        List.append(func(j))
    List1.append(List)
print(List1)
np.array(List1)

[[0.69278633]
 [0.37245352]
 [0.97732285]
 [0.3726891 ]
 [0.92929507]
 [0.8140083 ]
 [0.10117108]
 [0.62071235]
 [0.90169336]
 [0.85237341]]
********************************************************************************
[[1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192], [1.4264017047134192]]


array([[1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017],
       [1.4264017]])